version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    volumes:
      - type: bind
        source: ./backend
        target: /backend
    ports:
      - "8080:80"
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    volumes:
      - type: bind
        source: ./frontend
        target: /app
    ports:
      - "8181:5173"