version: '3'
services:
  backend:
    build:
      context: ./backend/legacy_spells
      dockerfile: ./Dockerfile
    volumes:
      - type: bind
        source: ./backend/legacy_spells
        target: /back-end
    ports:
      - "8080:80"
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    volumes:
      - type: bind
        source: ./frontend
        target: /app
    ports:
      - "8181:5173"