version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    volumes:
      - type: bind
        source: ./backend
        target: /back-end
    ports:
      - "8080:80"
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    volumes:
      - type: bind
        source: ./frontend/public
        target: /app/public
      - type: bind
        source: ./frontend/index.html
        target: /app/index.html
      - type: bind
        source: ./frontend/src
        target: /app/src
    ports:
      - "8181:5173"